### PR TITLE
QSettings fixes for QCheckbox, QPushButton and QSpinBox

### PR DESCRIPTION
**Pull request by pka**
Made some fixes for QSettingsManager. The FIXME comment is wrong. The problem came probably from using beginGroup/endGroup with add_handler, which seems not to work as expected.

### CODE REVIEW

**Comment by mfitzp** [comment]
Thanks for the fixes and examples @pka. I've seen similar issues with the QSettings interface myself, can you confirm if you're on PySide, PyQt4 or PyQt5? Unfortunately they all do things a little differently, and the return values of QSettings are platform dependent (sometimes strings, sometimes actual values).

I'm not sure I can merge this as it stands, as it breaks the 'goal' of pyqtconfig in that the stored values should always be of the correct type, e.g. when you do config.get('key') it _should_ return a boolean not a text string. This way you can use the values directly in code as well as keeping widgets in sync.

The built-in solution to this (which may or may not be working) is to use the default values for the config manager to map the variable retrieved from QSettings to the correct type. You can see the code for this on line 870 onwards. Have you set defaults for the values that are misbehaving? Does it fix it if you do?

**Comment by pka** [comment]
I'm working on Linux with PyQt4, the Plugin dev. environment of QGIS. I saw that default values solve some type conversion issues, but that's not so useful for me, because I set the default values of UI components in the ui file.
Reviewing my commit, I see that all type conversions are in the value setters, so all types stay correct.

**Comment by mfitzp** [comment]
The issue is that unless the values are altered as they come back out of
QSettings (before they get to the setting-widget state) then the pyqt
QSettingsManager can return 'true' 'True' or (bool) True or 1 depending on
the platform and PyQt version (this is what comes out of QSettings). That
means testing for those within any code that uses the value, rather can
being _sure_ that the returned value will be (bool) True. I'll have another
look at what is coming out on the various platforms and see if there is a
way to guess without resorting to defaults.

Which 'ui' file are you loading the default values from? I may be able to
write an importer for this into the defaults. You can optionally set the
defaults just for the types (the values will be ignored if you're loading
settings in anyway).

Do you have type conversion issues that aren't fixed by setting defaults?
They'll need looking at.

Thanks!

**Comment by mfitzp** [comment]
Hello again @pka  I've been looking some more at how to fix this issue and it occurred to me that a simple fix would be to allow defaults to be set automatically when the widget is connected - i.e. the default value is set to _whatever the widget is set to first_. From your description of settings the values from a ui file it sounds that that would work.

What do you think?

**Comment by pka** [comment]
This sounds perfect to me! As mentionend, I'm creating the UI with Qt Designer (converted to .py files with pyuic), so there should always be a sensible default value.

**Comment by mfitzp** [comment]
Great! I've added this to the latest release (v0.7). It was a single function-call change, where previously it set the _value_ of the config if it wasn't in the defaults, it now sets the default.  If you could test and see if it solves your problem that would be great.

I also took your start at the documentation and filled it out a bit more and added a demo application. It could do with some more work, but it should cover the most usual use-cases. I've credited your contribution to the documentation at the bottom (Acknowledgements).

I'll keep this PR open until you've confirmed the fix. Thanks!

**Comment by mfitzp** [comment]
Have you had chance to test the latest release @pka ?

**Comment by pka** [comment]
Got it working with some tweaks: 8fce492b2

**Comment by pka** [comment]
Did my tweaks break something?

**Comment by mfitzp** [comment]
@pka I saw your post on Twitter re this. Somehow I completely missed the new code. I'm happy to merge the changes, but are the modifications for `8fce492` still on this PR (I see that plus some other commits following). If you can confirm that I'll happily merge and do a new release. Thanks!

**Pull request merged**
